# Generated by Django 5.0.7 on 2024-07-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Base de Datos',
                'verbose_name_plural': 'Bases de Datos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la Categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Gestor de proyecto', 'Gestor del proyecto'), ('Analista de requerimientos', 'Analista de requerimientos'), ('Programador', 'Programador')], max_length=100)),
                ('contacto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='ServidorWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField()),
                ('estatus', models.CharField(choices=[('Operativo', 'Operativo'), ('Mantenimiento', 'Mantenimiento'), ('Inactivo', 'Inactivo'), ('Retirado', 'Retirado')], max_length=50)),
            ],
            options={
                'verbose_name': 'Servidor Web',
                'verbose_name_plural': 'Servidores Web',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Tecnologia')),
                ('tipo', models.CharField(choices=[('Base de datos', 'Base de datos'), ('Backend', 'Backend'), ('Frontend', 'Frontend')], max_length=100, verbose_name='Tipo')),
                ('lenguaje', models.CharField(max_length=100, verbose_name='Lenguaje')),
                ('version', models.CharField(max_length=50, verbose_name='Version de la Tecnologia')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('nota', models.TextField()),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versiones',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('direccion_url', models.URLField()),
                ('estatus', models.CharField(choices=[('Operativo', 'Operativo'), ('Mantenimiento', 'Mantenimiento'), ('Inactivo', 'Inactivo'), ('Retirado', 'Retirado')], max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.categoria')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.solicitante')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.version')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ResponsableProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.responsable')),
            ],
            options={
                'verbose_name': 'Responsable del Producto',
                'verbose_name_plural': 'Responsables de los Productos',
            },
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_datos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.basedatos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('servidor_web', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.servidorweb')),
            ],
            options={
                'verbose_name': 'Infraestructura del Producto',
                'verbose_name_plural': 'Infraestructuras de los Productos',
            },
        ),
        migrations.CreateModel(
            name='TecnologiaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.tecnologia')),
            ],
            options={
                'verbose_name': 'Tecnologia del Producto',
                'verbose_name_plural': 'Tecnologias de los Productos',
            },
        ),
    ]
