# Generated by Django 5.1 on 2024-10-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdependencia',
            options={'verbose_name': 'SubDependencia', 'verbose_name_plural': 'SubDependencias'},
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='sub_dependencia',
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitantes', to='productos.dependencia'),
        ),
        migrations.AlterField(
            model_name='subdependencia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la SubDependencia'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='sub_dependencia',
            field=models.ManyToManyField(blank=True, related_name='dependencias', to='productos.subdependencia'),
        ),
    ]
