# Generated by Django 5.1 on 2024-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estatus',
            field=models.CharField(choices=[(1, 'Operativo'), (2, 'Mantenimiento'), (3, 'Inactivo'), (4, 'Retirado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servidorweb',
            name='estatus',
            field=models.CharField(choices=[(1, 'Operativo'), (2, 'Mantenimiento'), (3, 'Inactivo'), (4, 'Retirado')], max_length=50),
        ),
    ]
