# Generated by Django 5.1 on 2024-10-04 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_subdependencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='sub_dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.subdependencia'),
        ),
    ]
