# Generated by Django 5.1 on 2024-10-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_solicitante_sub_dependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='sub_dependencia',
        ),
        migrations.AddField(
            model_name='subdependencia',
            name='dependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_dependencias', to='productos.dependencia'),
            preserve_default=False,
        ),
    ]
