# Generated by Django 5.1 on 2024-11-09 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo del Solicitante',
                'verbose_name_plural': 'Cargos de los Solicitantes',
            },
        ),
        migrations.AlterModelOptions(
            name='tecnologia',
            options={'verbose_name': 'Tecnología', 'verbose_name_plural': 'Tecnologías'},
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='contacto',
        ),
        migrations.AddField(
            model_name='responsable',
            name='telefono',
            field=models.CharField(default=1, max_length=15, verbose_name='Número de Teléfono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='extension',
            field=models.CharField(default=1, max_length=10, verbose_name='Extensión Telefónica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdependencia',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_dependencias', to='productos.dependencia'),
        ),
        migrations.AddConstraint(
            model_name='responsableproducto',
            constraint=models.UniqueConstraint(fields=('responsable', 'producto'), name='unique_responsable_producto'),
        ),
        migrations.AddConstraint(
            model_name='tecnologiaproducto',
            constraint=models.UniqueConstraint(fields=('tecnologia', 'producto'), name='unique_tecnologia_producto'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.cargosolicitante'),
        ),
    ]
